local Blips = {}

Blips.Icons = {
    { label = "Standard", value = 1 },
    { label = "Big Circle", value = 2 },
    { label = "Small Circle", value = 3 },
    { label = "Police Officer", value = 4 },
    { label = "Police Area", value = 5 },
    { label = "Square", value = 6 },
    { label = "Player Position", value = 7 },
    { label = "North", value = 8 },
    { label = "Waypoint", value = 9 },
    { label = "Big Circle Outline", value = 10 },
    { label = "Arrow Up Outline", value = 11 },
    { label = "Arrow Down Outline", value = 12 },
    { label = "Arrow Up", value = 13 },
    { label = "Arrow Down", value = 14 },
    { label = "Police Helicopter", value = 15 },
    { label = "Chat Bubble", value = 16 },
    { label = "Garage", value = 17 },
    { label = "Drugs", value = 18 },
    { label = "Store", value = 19 },
    { label = "Weapon", value = 21 },
    { label = "Hospital", value = 22 },
    { label = "Star", value = 23 },
    { label = "Flag", value = 24 },
    { label = "Helicopter", value = 43 },
    { label = "Boat", value = 427 },
    { label = "Parachute", value = 251 },
    { label = "Motorcycle", value = 226 },
    { label = "Bike", value = 348 },
    { label = "Car", value = 225 },
    { label = "Truck", value = 477 },
    { label = "Car Wash", value = 100 },
    { label = "Clothing Store", value = 73 },
    { label = "Barber Shop", value = 71 },
    { label = "Tattoo Shop", value = 75 },
    { label = "Bank", value = 108 },
    { label = "ATM", value = 277 },
    { label = "Restaurant", value = 52 },
    { label = "Fire Station", value = 60 },
    { label = "Prison", value = 237 },
    { label = "Airport", value = 90 },
    { label = "Gas Station", value = 361 },
    { label = "Bar", value = 93 },
    { label = "Amusement Park", value = 102 },
    { label = "Cinema", value = 135 },
    { label = "Museum", value = 136 },
    { label = "Theater", value = 137 },
    { label = "Park", value = 160 },
    { label = "Hotel", value = 475 },
    { label = "Bus Station", value = 513 },
    { label = "Train Station", value = 515 },
    { label = "Subway Station", value = 512 },
    { label = "School", value = 430 },
    { label = "College", value = 431 },
    { label = "University", value = 432 },
    { label = "Library", value = 433 },
    { label = "Church", value = 304 },
    { label = "Mosque", value = 305 },
    { label = "Temple", value = 306 },
    { label = "Synagogue", value = 307 },
    { label = "Hospital", value = 61 },
    { label = "Clinic", value = 362 },
    { label = "Pharmacy", value = 363 },
    { label = "Dental Clinic", value = 364 },
    { label = "Veterinary Clinic", value = 365 },
    { label = "Police Station", value = 60 },
    { label = "Ambulance Station", value = 74 },
    { label = "Fire Station", value = 59 },
    { label = "Government Building", value = 304 },
    { label = "Court", value = 305 },
    { label = "City Hall", value = 306 },
    { label = "Library", value = 307 },
    { label = "School", value = 430 },
    { label = "College", value = 431 },
    { label = "University", value = 432 },
    { label = "Library", value = 433 },
}

Blips.Colors = {
    { label = "White", value = 0 },
    { label = "Red", value = 1 },
    { label = "Green", value = 2 },
    { label = "Blue", value = 3 },
    { label = "Yellow", value = 5 },
    { label = "Purple", value = 7 },
    { label = "Orange", value = 17 },
    { label = "Dark Red", value = 76 },
    { label = "Pink", value = 24 },
    { label = "Gray", value = 3 },
    { label = "Dark Purple", value = 83 },
    { label = "Dark Green", value = 52 },
    { label = "Dark Blue", value = 26 },
    { label = "Light Blue", value = 4 },
    { label = "Light Green", value = 30 },
    { label = "Dark Yellow", value = 35 },
    { label = "Light Red", value = 6 },
    { label = "Light Orange", value = 8 },
    { label = "Dark Orange", value = 9 },
    { label = "Gold", value = 46 },
    { label = "Silver", value = 47 },
    { label = "Bronze", value = 48 },
    { label = "Dark Brown", value = 49 },
    { label = "Light Brown", value = 50 },
    { label = "Dark Gray", value = 51 },
    { label = "Light Gray", value = 52 },
    { label = "Dark Pink", value = 84 },
    { label = "Light Pink", value = 85 },
}

return Blips